import { EmbedBuilder } from "discord.js";

const COLORS = {
    carnivore: '#ff0033',
    herbivore: '#1e672f',
    general: '#efbe70',
    pack: '#6234bd',
};

const RULES_VERSION = "v1.0";
const RULES_UPDATED = "2026-02-01";


export const rulesPosts = [
    {
        key: "rules_herbivore",
        channelId: "1462648723254411366",
        embed: new EmbedBuilder()
            .setColor(COLORS.herbivore)
            .setTitle("🌿 Herbivore Rules")
        	.setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469882190878740695/Pachycephalosaurus-ec20045c.png?ex=698945f7&is=6987f477&hm=e321e9a0d05091bcfa42e1a24daea414d41dd28a50d287d0e58db76bdc73674c&=&format=webp&quality=lossless")
            .setDescription(
                [
                    "⚖️ **Core Philosophy**",
                    "> • Herbivores are defensive by nature, but would still fight for survival, territory, or resources when necessary.",
                    "> • Survival > domination",
                    "",
                    "",
                    "🩸 **1) Combat **",
                    "> • Herbivores **MAY** initiate combat.",
                    "> • You are **DIRECTLY ALLOWED** to attack other dino's on sight.",
                    "",
                    "",
                    "🔁 **2) Disengage & Cooldown**",
                    "> • Chasing after safety is achieved = revenge killing",
                    "> • After successful defense, herbivores should relocate or de-escalate",
                    "",
                    "",
                    "🦴 **3) Area & Body Rules**",
                    "> • Body or carcass camping is **allowed**, this includes using body's as bait.",
                    ">   ◦ This includes all herbivores except **Triceratops** and **stegosaurus**",
                    "> • Passing through a carcass area is allowed — lingering is not.",
                    ">   ◦ unless your recovering from a fight",
                    "",
                    "",
                    "👥 **4) Group Limits & Herd Behavior**",
                    "> • All species must follow server group limits",
                    ">   ◦ see **Pack Limit Rules** for details - <#1466464861289447664>",
                    "",
                    "",
                    "🐣 **5) Juvenile Protection**",
                    "> • Adults may defend juveniles of their own species only",
                    "> • Juveniles may NOT be used as bait, shields, or aggro tools",
                    "",
                    "",
                    "⚠️ **6) Escalation & Behavior**",
                    "> • Herbivores must show clear escalation when possible:",
                    ">   ◦ Threat calls",
                    ">   ◦ Posturing",
                    ">   ◦ Warning charges",
                    "> • Instant lethal force without escalation may be ruled unrealistic",
                    "",
                    "",
                    "💧 **7) Water Etiquette**",
                    "> • Permanent water denial is not allowed",
                    "> • Large herds must allow reasonable access to others",
                    "",
                    "",
                    "🔌 **8) Combat Logging**",
                    "> • Logging is **NOT allowed** while:",
                    ">   ◦ In combat",
                    ">   ◦ Being actively hunted",
                    ">   ◦ Using the parking system to avoid combat",
                    "",
                    "",
                    "🧠 **9) Common Sense & Staff Discretion**",
                    "> • Clearly exploitative, meta, or unrealistic behavior may be punished",
                    "> • Staff decisions are final, even if a scenario is not listed",
                    "",
                    "",
                    "🦕🦖 **10) Stegosaurus & Triceratops Mixed Herd Exception**",
                    "> • Allowed: **ONE (1) Stego + ONE (1) Trike**",
                    "> • No additional Stegos, Trikes, or other herbivores may join",
                    "> • This exception is for travel and defense only",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **11)Clarifications**",
                    "> • If one dies, the pair may not be replaced until the group fully disbands",
                    "> • All herbivore combat and escalation rules still apply",
                    "> • Abuse of this exception may result in punishment or loss of privileges",
                ].join("\n")
            )
            .setFooter({ text: `Staff may enforce additional rulings if needed. Play fair, stay realistic, survive 🌿\n Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
            .setTimestamp(),
    },

    {
        key: "rules_carnivore",
        channelId: "1462648847414202388",
        embed: new EmbedBuilder()
            .setColor(COLORS.carnivore)
            .setTitle("🥩 Carnivore Rules")
        	.setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469882209791115324/Pteranodon-75fd074e.png?ex=698945fb&is=6987f47b&hm=8eaf5ad83f8a224c33fb10fb803cad59eb785b8f86edceae15a6540ec2bfd3a2&=&format=webp&quality=lossless")
            .setDescription(
                [
                    "⚖️ **Core Philosophy**",
                    "> • Carnivores exist to hunt — but every kill must have meaning: hunger, defense, or dominance of territory.",
                    "> • Survival > excess",
                    "",
                    "",
                    "🍖 **1) Hunting & Combat**",
                    "> • Hunt for food, survival, territory, or self-defense",
                    "> • Do not repeatedly target the same player/group after a successful kill",
                    "> • **Third partying is NOT allowed unless you engage with both parties** — othwerise do not interfere in other fights",
                    "",
                    "",
                    "🩸 **2) Body & Feeding Rules**",
                    "> • The body belongs to the killer or hunting group",
                    "> • Challenging for a body is allowed only after the initial fight has ended",
                    "> • No guarding bodies indefinitely — eat, then move on",
                    "",
                    "",
                    "👥 **3) Grouping**",
                    "> • No mix-packing or mix-coordinating with other species (unless stated otherwise)",
                    "> • Groups must stay reasonably close — no map-wide coordination",
                    "> • Hatchling protection must be realistic, not exploited",
                    "",
                    "",
                    "🏃 **4) Chasing & Escaping**",
                    "> • No chase baiting or stamina draining without intent to kill",
                    "> • If prey escapes and breaks line of sight, the hunt should reasonably end",
                    "> • No body-blocking or terrain exploits for unfair kills",
                    "",
                    "",
                    "⚖️ **5) General Conduct**",
                    "> • No exploiting bugs, hitboxes, or animations",
                    "> • No stream sniping or metagaming",
                    "> • No rule lawyering during fights — report issues after",
                    "> • Admins have final say in all situations",
                ].join("\n")
            )
            .setFooter({ text: `Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
            .setTimestamp(),
    },

    {
        key: "rules_general",
        channelId: "1462648417120682014",
        embed: new EmbedBuilder()
            .setColor(COLORS.general) // neutral / official
            .setTitle("📜 General Server Rules")
        	.setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469881920799375452/Beipiaosaurus-62e0cfb3.png?ex=698945b7&is=6987f437&hm=415cccb6650d75c31adbaddf743dc4e6f2f2ecb2dd66902bce0e4ae6709be2d9&=&format=webp&quality=lossless")
            .setDescription(
                [
                    "<a:68523animatedarrowgreen:1467450531667771665> **Welcome to the server!**",
                    "To keep the community fun, fair, and enjoyable for everyone, all players must follow the rules below.",
                    "By joining, you agree to comply with these rules at all times.",
                    "",
                    "",
                    "🎮 **Gameplay Rules**",
                    "> • **No Mixpacking** — different carnivore species may not pack, hunt, travel, or fight together.",
                    "> • **No Exploits or Loopholes** — attempting to find, abuse, or manipulate exploits or loopholes in rules or mechanics is strictly prohibited.",
                    "> • **Evidence** — Using f2 to record gameplay is a must. This allows us to come to a verdict on any rulebreak/bug that occurs.",
                    "",
                    "",
                    "💬 **Chat & Community Rules**",
                    " The following are not allowed:",
                    ">  ◦ Spamming in chat",
                    ">  ◦ Location dropping",
                    ">  ◦ Excessive swearing",
                    ">  ◦ Instigating arguments",
                    ">  ◦ Ignoring staff instructions",
                    ">  ◦ Disrespect toward staff",
                    ">  ◦ Impersonating staff or team members",
                    ">  ◦ Insulting or belittling others",
                    ">  ◦ Bullying, harassment, or malicious behavior",
                    ">  ◦ Discrimination of any kind",
                    ">  ◦ Derogatory language",
                    ">  ◦ Spreading misinformation",
                    ">  ◦ Religion, politics, or war-related discussions",
                    ">  ◦ Recruitment or advertisement",
                    ">  ◦ Self-promotion without staff permission",
                    ">  ◦ Malicious or harmful links",
                    ">  ◦ Inappropriate content, usernames, profile pictures, or statuses",
                    ">  ◦ NSFW comments, posts, messages, or content",
                    ">  ◦ Encouragement of self-harm or suicide (e.g. “kys”)",
                    ">  ◦ Statuses promoting terrorism, discrimination, or harmful intent",
                    ">  ◦ Ban evasion",
                    ">  ◦ Intentionally ignoring or breaking server rules",
                    ">  ◦ Enlgish language only in text channels. Voice channels are not prohibited to follow this rule",
                    "",
                    "",
                    "🚨 **Zero Tolerance Policy**",
                    " Any form of:",
                    ">  ◦ Hate speech",
                    ">  ◦ Discrimination",
                    ">  ◦ Harassment",
                    ">  ◦ Exploitation",
                    ">  ◦ Malicious behavior",
                    ">  ◦ Harmful content",
                    " will result in strict moderation action, including bans if necessary.",
                    "",
                    "",
                    "🛡️ **Staff Authority**",
                    "> • Staff decisions must be respected at all times",
                    "> • Arguing or ignoring staff instructions may result in punishment",
                    "> • If you believe a mistake was made, address it calmly through proper channels",
                    "",
                    "",
                    "📌 **Final Note**",
                    "> These rules exist to protect the community, ensure fair gameplay, and keep the server enjoyable for everyone.",
                    "> Respect others, play fair, and help build a strong, positive server culture.",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **Happy hunting and enjoy your time on the server!**",
                ].join("\n")
            )
            .setFooter({ text: `Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
            .setTimestamp(),
    },

    {
        key: "rules_Packlimits",
        channelId: "1466464861289447664",
        embed: new EmbedBuilder()
            .setColor(COLORS.pack)
            .setTitle("☯️ Pack Limit Server Rules")
        	.setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469881707279810641/Troodon-5fd83e64.png?ex=69894584&is=6987f404&hm=73c79963c842f7b1c6ee76f385502c762ba33add8320136413d17deb7201d801&=&format=webp&quality=lossless")
            .setDescription(
                [
                    "<a:68523animatedarrowgreen:1467450531667771665> **Herbivore Herding Rules**",
                    "Herbivores may form groups with their own species, with the limit applying per group.",
                    "This must be a single, unified herd — **NO MIXED PACKING!** Mixed-species herds are described below;",
                    "",
                    "",
                    "⚪ **Single-Species Herds**",
                    "> ◦ **All Juveniles below 40% Growth** - **Unlimited** per group",
                    "> ◦ **Dryosaurus** - **Unlimited** per pack",
                    "> ◦ **Beipiaosaurus** - **Unlimited** per pack",
                    "> ◦ **Hypsilophodon** - **Unlimited** per pack",
                    "> ◦ **Gallimimus** - **15** per pack",
                    "> ◦ **Pachycephalosaurus** - **10** per pack",
                    "> ◦ **Maiasaura** - **6** per pack",
                    "> ◦ **Tenontosaurus** - **6** per pack",
                    "> ◦ **Diabloceratops** - **5** per pack",
                    "> ◦ **Stegosaurus** - **3** per pack",
                    "> ◦ **Triceratops** - **2** per pack",
                    "",
                    "",
                    "🔴 **Mixed-Species Herds**",
                    "> Herds may have up to **40** points maximum.",
                    "> Splitting groups and temporarily hopping is **forbidden**.",
                    "> Species with **0** points do not count towards the 40-point limit.",
                    "",
                    "",
                    "🟢 **Mixed Herd Points**",
                    "> ◦ **All Juveniles below 40% Growth** - 0 points",
                    "> ◦ **Dryosaurus** - **0** points.",
                    "> ◦ **Beipiaosaurus** - **0** points.",
                    "> ◦ **Hypsilophodon** - **0** points",
                    "> ◦ **Gallimimus** - **5** points",
                    "> ◦ **Pachycephalosaurus** - **5** points",
                    "> ◦ **Maiasaura** - **7** points",
                    "> ◦ **Tenontosaurus** - **10** points",
                    "> ◦ **Diabloceratops** - **15** points",
                    "> ◦ **Stegosaurus** - **20** points",
                    "> ◦ **Triceratops** - **20** points",
                    "",
                    "",
                    "🟣 **Special Single-Permit Groups**",
                    " The following may form a group together, but only 1 of each species is allowed",
                    "> ◦ **Stegosaurus**",
                    "> ◦ **Triceratops**",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **Carnivore Pack limits**",
                    "You may only form a group with your own species, up to the limits below;",
                    "❕Pteranodons are not included in this rule ❕",
                    "",
                    "",
                    "🟠 **Carnivore's**",
                    "> ◦ **Pteranodon** — **Unlimited**",
                    "> ◦ **Troodon** — **20** per pack",
                    "> ◦ **Omniraptor** — **10** per pack",
                    "> ◦ **Herrerasaurus** — **12** per pack",
                    "> ◦ **Dilophosaurus** — **6** per pack",
                    "> ◦ **Ceratosaurus** — **4** per pack",
                    "> ◦ **Carnotaurus** — **6** per pack",
                    "> ◦ **Allosaurus** — **4** per pack",
                    "> ◦ **Deinosuchus** — **3** per pack",
                    "> ◦ **Tyrannosaurus Rex** — **2** per pack",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **Pack limit violations may result in moderation action!**",
                ].join("\n")
            )
            .setFooter({ text: `Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
            .setTimestamp(),
    },
];
