import { EmbedBuilder } from "discord.js";

const COLORS = {
    carnivore: '#ff0033',
    herbivore: '#1e672f',
    general: '#efbe70',
    pack: '#6234bd',
};

const RULES_VERSION = "v2.0";
const RULES_UPDATED = "12/04/2026";

const HANG = " ";
const INDENT = " ";
const INDENT2 = "  ";

export const rulesPosts = [
    {
        key: "rules_herbivore",
        channelId: "1462648723254411366",
        embed: new EmbedBuilder()
            .setColor(COLORS.herbivore)
            .setTitle("🌿 Herbivore Rules - Includes Omnivores")
            .setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469882190878740695/Pachycephalosaurus-ec20045c.png?ex=698945f7&is=6987f477&hm=e321e9a0d05091bcfa42e1a24daea414d41dd28a50d287d0e58db76bdc73674c&=&format=webp&quality=lossless")
            .setImage("https://cdn.discordapp.com/attachments/778652435227869214/1485688543958270002/HerbivoreRules.png?ex=69c2c6c7&is=69c17547&hm=bcf134445fb23f4672100fb207326ba08a414c109d333ecc0336ad1670b814b0&")
            .setDescription(
                [
                    "⚖️ **Core Philosophy**",
                    `> • Herbivores are defensive by nature, but would ${HANG}${HANG}still fight for survival, territory, or resources`,
                    `> ${HANG}${HANG}when necessary.`,
                    "> • Survival > domination",
                    "",
                    "",
                    "🩸 **1) Combat **",
                    "> • Herbivores **MAY** initiate combat.",
                    `> • You are **DIRECTLY ALLOWED** to attack other ${HANG}${HANG}dinosaurs on sight.`,
                    `> • You are **NOT** allowed to change skins during`,
                    `> ${HANG}${HANG}combat, with the purpose of`,
                    `> ${HANG}${HANG}escaping/missleading your opposition.`,
                    "> • **No group hopping during combat**",
                    `> ${HANG}╭ Only after the fight has ended, new`, 
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}members can join your current group.`,
                    `> ${HANG}${HANG}${HANG}⧽ Unparking a dinosaur and rejoining your`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}group is also classed as group hopping.`,
                    `> ${HANG}╰ You can only rejoin your group once the`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}fight has ended.`,
                    "",
                    "",
                    "🦴 **2) Area & Body Rules**",
                    "> • Body or carcass camping is **allowed**,",
                    `> ${HANG}${HANG}this includes using body's as bait.`,
                    `> ${HANG}╭ This also includes all herbivores except`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}*Triceratops* and *Stegosaurus*.`,
                    `> ${HANG}${HANG}${HANG}⧽ *Triceratops* and *Stegosaurus* can stay near`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}corpses, **ONLY** if the fight is still active.`,
                    `> ${HANG}╰ Once the fight has finished, *Triceratops*`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}and *stegosaurus* can heal then move on.`,
                    "> • Passing through a carcass area is allowed as",
                    `> ${HANG}${HANG}a *Triceratops* or *Stegosaurus*, lingering is not.`,
                    `> ${HANG}╰ Unless your recovering from a fight`,
                    "",
                    "",
                    "👥 **3) Group Limits & Herd Behavior**",
                    "> • All species must follow server group limits",
                    `> ╭ see **Pack Limit Rules** for details`,
                    `> ╰ <#1466464861289447664>`,
                    "",
                    "",
                    "🐣 **4) Juvenile Protection**",
                    "> • Adults may only protect juvenial's that are",
                    `> ${HANG}${HANG}under 40% growth.`,
                    `> ${HANG}╭ After 40% these count towards the mix`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG}${HANG}pack herd limits.`,
                    `> ${HANG}╰ see <#1466464861289447664>`,
                    "",
                    "",
                    "🔌 **5) Combat Logging**",
                    "> • Logging is **NOT allowed** while:",
                    `> ${HANG}╭ In combat, unless your in a position of`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} safety - E.g. A Pachycephalosaurus jumping`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} onto a rock.`,
                    `> ${HANG}╰ This also means being inside of a bush and`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} having time to logout.`,
                    ">  • Using the parking system to avoid combat",
                    "",
                    "",
                    "❌ **6) Scouting or luring**",
                    `> • Scouting or luring as a Beipiaosaurus for`,
                    `> ${HANG} other species is not allowed.`,
                    `> ${HANG}╭ E.g. A Beipiaosaurus acting friendly with`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} the intention to lure dinosaurs to the water`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} for a Deinosuchus.`,
                    "",
                    "",
                    "⚖️ **7) General Conduct**",
                    "> • No exploiting bugs, hitboxes, or animations.",
                    "> • No stream sniping or metagaming.",
                    "> • No rule lawyering during fights — report",
                    `> ${HANG} issues after.`,
                    `> ${HANG}╭ Report issues using the correct channels`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} - <#1467572329444938024>.`,
                    `> ${HANG}╰ Direct messages to any member of staff`,
                    `> ${HANG}${HANG}${HANG}${HANG}${HANG} will not be accepted.`,
                    "> • Staff and admins have final say in all",
                    `> ${HANG} situations.`,
                    "",
                    "",
                ].join("\n")
            )
            .setFooter({ text: `Staff may enforce additional rulings if needed. Play fair, stay realistic, survive 🌿\n Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
    },

    {
        key: "rules_carnivore",
        channelId: "1462648847414202388",
        embed: new EmbedBuilder()
            .setColor(COLORS.carnivore)
            .setTitle("🥩 Carnivore Rules")
            .setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469882209791115324/Pteranodon-75fd074e.png?ex=698945fb&is=6987f47b&hm=8eaf5ad83f8a224c33fb10fb803cad59eb785b8f86edceae15a6540ec2bfd3a2&=&format=webp&quality=lossless")
            .setImage("https://cdn.discordapp.com/attachments/778652435227869214/1485687300561174598/CarnivoreRules.png?ex=69c2c59f&is=69c1741f&hm=534d5b58de26a806891fcc8adbd88b2cb1dd4a7643500234aeaa691308dbc919&")
            .setDescription(
                [
                    "⚖️ **Core Philosophy**",
                    "> • Carnivores exist to hunt — but every kill must have meaning: hunger, defense, or dominance of territory.",
                    "> • Survival > excess",
                    "",
                    "",
                    "🍖 **1) Hunting & Combat**",
                    "> • Hunt for food, survival, territory, or self-defense.",
                    "> • **Third partying is NOT allowed unless you engage with both parties** — othwerise do not interfere in other fights.",
                    "> • You are **NOT** allowed to change skins during combat, with the purpose of escaping/missleading your opposition.",
                    "> • **No group hopping during combat**",
                    `> ${INDENT}◦ Only after the fight has ended, new members can join your current group`,
                    `> ${INDENT}◦ Unparking a dinosaur and rejoining your group is also classed as group hopping.`,
                    `> ${INDENT}◦ You can only rejoin your group once the fight has ended.`,
                    "",
                    "",
                    "👥 **2) Grouping**",
                    "> • No mix-packing or mix-coordinating with other species (unless stated otherwise).",
                    "",
                    "",
                    "🏃 **3) Chasing & Escaping**",
                    "> • No chase baiting or stamina draining without intent to kill.",
                    "> • No body-blocking or terrain exploits for unfair kills.",
                    "",
                    "",
                    "🐣 **4) Juvenile Protection**",
                    "> • Adults may only protect juvenial's that are under 40% growth, and are of the same species.",
                    `> ${INDENT}◦ After 40% these count towards the pack limits.`,
                    `> ${INDENT}◦ see **Pack Limit Rules** for details`,
                    `> ${INDENT}◦ <#1466464861289447664>`,
                    "",
                    "",
                    "🔌 **5) Combat Logging**",
                    "> • Logging is **NOT allowed** while:",
                    `> ${INDENT}◦ In combat, unless your in a position of safety - E.g. A Omniraptor jumping onto a rock.`,
                    `> ${INDENT}◦ Using the parking system to avoid combat`,
                    "",
                    "",
                    "❌ **6) Scouting or luring**",
                    "> • Scouting or luring as a Beipiaosaurus or Pteranodon for other species is not allowed.",
                    `> ${INDENT}◦ E.g. A Pteranodon 1 calling above dinosaurs to alert players of their location.`,
                    "",
                    "",
                    "⚖️ **7) General Conduct**",
                    "> • No exploiting bugs, hitboxes, or animations.",
                    "> • No stream sniping or metagaming.",
                    "> • No rule lawyering during fights — report issues after.",
                    `> ${INDENT}◦ Report issues using the correct channels - <#1467572329444938024>.`,
                    `> ${INDENT}◦ Direct messages to any member of staff will not be accepted.`,
                    "> • Staff and admins have final say in all situations.",
                    "",
                    "",
                ].join("\n")
            )
            .setFooter({ text: `Staff may enforce additional rulings if needed. Play fair, stay realistic, survive 🥩\n Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
    },

    {
        key: "rules_general",
        channelId: "1462648417120682014",
        embed: new EmbedBuilder()
            .setColor(COLORS.general)
            .setTitle("📜 General Server Rules")
            .setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469881920799375452/Beipiaosaurus-62e0cfb3.png?ex=698945b7&is=6987f437&hm=415cccb6650d75c31adbaddf743dc4e6f2f2ecb2dd66902bce0e4ae6709be2d9&=&format=webp&quality=lossless")
            .setImage("https://cdn.discordapp.com/attachments/778652435227869214/1485701019202621471/GeneralRules.png?ex=69c2d265&is=69c180e5&hm=2d204ac693a10f512faa1ca358f6d5aa8f800287ad7a234d8329f170a0a30a8d&")
            .setDescription(
                [
                    "<a:68523animatedarrowgreen:1467450531667771665> **Welcome to the server!**",
                    "To keep the community fun, fair, and enjoyable for everyone, all players must follow the rules below.",
                    "By joining, you agree to comply with these rules at all times.",
                    "",
                    "",
                    "🎮 **Gameplay Rules**",
                    "> • **No Mixpacking** — Different carnivore species may not pack, hunt, travel, or fight together.",
                    "> • **No Exploits or Loopholes** — Attempting to find, abuse, or manipulate exploits or loopholes in rules or mechanics is strictly prohibited.",
                    "> • **Evidence** — Using f2 to record gameplay is a must. This allows us to come to a verdict on any rulebreak/bug that occurs.",
                    `> ${INDENT}◦ Other clipping softwares can be used in certain situations.`,
                    "",
                    "",
                    "💬 **Chat & Community Rules**",
                    " The following are not allowed:",
                    "> • Spamming in chat",
                    "> • Location dropping",
                    "> • Excessive swearing",
                    "> • Instigating arguments",
                    "> • Ignoring staff instructions",
                    "> • Disrespect toward staff",
                    "> • Impersonating staff or team members",
                    "> • Insulting or belittling others",
                    "> • Bullying, harassment, or malicious behavior",
                    "> • Discrimination of any kind",
                    "> • Derogatory language",
                    "> • No promoting other servers in game or discord.",
                    "> • Spreading misinformation",
                    "> • Religion, politics, or war-related discussions",
                    "> • Recruitment or advertisement",
                    "> • Self-promotion without staff permission",
                    "> • Malicious or harmful links",
                    "> • Inappropriate content, usernames, profile pictures, or statuses",
                    "> • NSFW comments, posts, messages, or content",
                    "> • Encouragement of self-harm or suicide (e.g. “kys”)",
                    "> • Statuses promoting terrorism, discrimination, or harmful intent",
                    "> • Ban evasion",
                    "> • Intentionally ignoring or breaking server rules",
                    "> • English language only in text channels. Voice channels are not prohibited to follow this rule",
                    "",
                    "",
                    "🚨 **Zero Tolerance Policy**",
                    " Any form of:",
                    "> • Hate speech",
                    "> • Discrimination",
                    "> • Harassment",
                    "> • Exploitation",
                    "> • Malicious behavior",
                    "> • Harmful content",
                    " will result in strict moderation action, including bans if necessary.",
                    "",
                    "",
                    "🛡️ **Staff Authority**",
                    "> • Staff decisions must be respected at all times",
                    "> • Arguing or ignoring staff instructions may result in punishment",
                    "> • If you believe a mistake was made, address it calmly through proper channels",
                    "",
                    "",
                    "📌 **Final Note**",
                    "> These rules exist to protect the community, ensure fair gameplay, and keep the server enjoyable for everyone.",
                    "> Respect others, play fair, and help build a strong, positive server culture.",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **Happy hunting and enjoy your time on the server!**",
                ].join("\n")
            )
            .setFooter({ text: `Staff may enforce additional rulings if needed.\n Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })
    },

    {
        key: "rules_Packlimits",
        channelId: "1466464861289447664",
        embed: new EmbedBuilder()
            .setColor(COLORS.pack)
            .setTitle("☯️ Pack Limit Server Rules")
            .setThumbnail("https://media.discordapp.net/attachments/778652435227869214/1469881707279810641/Troodon-5fd83e64.png?ex=69894584&is=6987f404&hm=73c79963c842f7b1c6ee76f385502c762ba33add8320136413d17deb7201d801&=&format=webp&quality=lossless")
            .setImage("https://cdn.discordapp.com/attachments/778652435227869214/1485690305004044298/PackLimits.png?ex=69c2c86b&is=69c176eb&hm=1f1c41f599a2d6386ae54b879ef22ec284b427b4170eba0e2186e73b6913ae95&")
            .setDescription(
                [
                    "<a:68523animatedarrowgreen:1467450531667771665> **Herbivore Herding Rules**",
                    "Herbivores may form groups with their own species, with the limit applying per group.",
                    "This must be a single, unified herd — **NO MIXED PACKING!** Mixed-species herds are described below;",
                    "",
                    "",
                    "⚪ **Single-Species Herds**",
                    "> • **All Juveniles below 40% Growth** - **Unlimited** per group",
                    "> • **Dryosaurus** - **Unlimited** per pack",
                    "> • **Beipiaosaurus** - **Unlimited** per pack",
                    "> • **Hypsilophodon** - **Unlimited** per pack",
                    "> • **Gallimimus** - **15** per pack",
                    "> • **Pachycephalosaurus** - **11** per pack",
                    "> • **Maiasaura** - **6** per pack",
                    "> • **Tenontosaurus** - **6** per pack",
                    "> • **Diabloceratops** - **4** per pack",
                    "> • **Stegosaurus** - **3** per pack",
                    "> • **Triceratops** - **2** per pack",
                    "",
                    "",
                    "🔴 **Mixed-Species Herds**",
                    "> Herds may have up to **40** points maximum.",
                    "> Splitting groups and temporarily hopping is **forbidden**.",
                    "> Species with **0** points do not count towards the 40-point limit.",
                    "",
                    "",
                    "🟢 **Mixed Herd Points**",
                    "> • **All Juveniles below 40% Growth** - 0 points",
                    "> • **Dryosaurus** - **0** points.",
                    "> • **Beipiaosaurus** - **0** points.",
                    "> • **Hypsilophodon** - **0** points",
                    "> • **Gallimimus** - **2** points",
                    "> • **Pachycephalosaurus** - **5** points",
                    "> • **Maiasaura** - **15** points",
                    "> • **Tenontosaurus** - **10** points",
                    "> • **Diabloceratops** - **15** points",
                    "> • **Stegosaurus** - **20** points",
                    "> • **Triceratops** - **20** points",
                    "",
                    "",
                    "🟣 **Special Single-Permit Groups**",
                    " The following may form a group together, but only 1 of each species is allowed",
                    "> • **Stegosaurus**",
                    "> • **Triceratops**",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **Carnivore Pack limits**",
                    "> • You may only form a group with your own species, up to the limits below;",
                    `> ${INDENT}◦ **Pteranodons are not included in this rule**`,
                    "",
                    "",
                    "🟠 **Carnivore's**",
                    "> • **Pteranodon** — **Unlimited**",
                    "> • **Troodon** — **20** per pack",
                    "> • **Omniraptor** — **12** per pack",
                    "> • **Herrerasaurus** — **12** per pack",
                    "> • **Dilophosaurus** — **6** per pack",
                    "> • **Ceratosaurus** — **4** per pack",
                    "> • **Carnotaurus** — **6** per pack",
                    "> • **Allosaurus** — **4** per pack",
                    "> • **Deinosuchus** — **3** per pack",
                    "> • **Tyrannosaurus Rex** — **2** per pack",
                    "",
                    "",
                    "<a:68523animatedarrowgreen:1467450531667771665> **Pack limit violations may result in moderation action!**",
                ].join("\n")
            )
            .setFooter({ text: `Staff may enforce additional rulings if needed. Play fair, stay realistic, survive ☯️\n Rules Version: ${RULES_VERSION} | Updated: ${RULES_UPDATED}` })

    },
];