export default {
  Allosaurus: "Carnivore",
  Beipiaosaurus: "Omnivore",
  Carnotaurus: "Carnivore",
  Ceratosaurus: "Carnivore",
  Deinosuchus: "Carnivore",
  Diabloceratops: "Herbivore",
  Dilophosaurus: "Carnivore",
  Dryosaurus: "Herbivore",
  Gallimimus: "Omnivore",
  Herrerasaurus: "Carnivore",
  Hypsilophodon: "Herbivore",
  Maiasaura: "Herbivore",
  Omniraptor: "Carnivore",
  Pachycephalosaurus: "Herbivore",
  Pteranodon: "Carnivore",
  Stegosaurus: "Herbivore",
  Tenontosaurus: "Herbivore",
  Triceratops: "Herbivore",
  Troodon: "Carnivore",
  Tyrannosaurus: "Carnivore",
};